exclude: |
  (?x)^(
    \.terraform/.*|
    \.terragrunt-cache/.*|
    .*\.tfstate|
    .*\.tfstate\.backup|
    .*\.tfvars\.json|
    .*/\.terraform/.*|
    .*/plans/.*|
    .*lock\.hcl|
    \.pre-commit-config\.yaml
  )$

repos:
  # Basic file and security hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: end-of-file-fixer

  # Terraform quick checks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - '--args=--call-module-type=all'

  # Secret detection
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        args: [--verbose, --source=.]

  # Local hooks
  - repo: local
    hooks:
      - id: validate-commit-message
        name: Validate Commit Message
        entry: python scripts/validate_commit_message.py
        language: python
        stages: [commit-msg]